export const FETCH_NOTES = "FETCH_NOTES"
export const ADD_NOTE = 'ADD_NOTE'
export const REMOVE_NOTE = 'REMOVE_NOTE'
export const TOGGLE_IS_LOADING = 'TOGGLE_IS_LOADING'
export const EDIT_NOTES = 'EDIT_NOTES'
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE'
export const TOGGLE_IS_COMPLETED = 'TOGGLE_IS_COMPLETED'